const mongoose=require("mongoose");
const ObjectId=mongoose.Schema.Types.ObjectId
const productSchema=new mongoose.Schema({
    productName:{
        type:String
    },
    image1:{
        type:String
    },
    image2:{
        type:String
    },
    image3:{
        type:String
    },
    image4:{
        type:String
    },
    category:{
        type:String
    },
    productDiscription:{
        type:String
    },
    subcategory:{
        type:String
    },
    remaingStock:{
        type:Number,
        default:0
    },
    totalStock:{
        type:Number,
        default:0
    },
    price:{
        type:Number,
        default:0
    },
    gst:{
        type:Number,
        default:0
    },
    discount:{
        type:Number,
        default:0
    },
    hsnCode:{
        type:String
    },
    brand:{
        type:String
    },
    productModel:{
        type:String
    },
    addedBy:{
        type:String
    },
    vendorId:{
        type:ObjectId,
        ref:"vendor"
    },
    specification:[{
         point:{
        type:String
    },
    }],
   
    howToUse:[{
        point1:{
       type:String
   },
   }],
   status:{
       type:String,
       default:"Inactive"
   }

},{timestamps:true});
module.exports=mongoose.model("product",productSchema);
